version: '3'

services:
  aws-lambda-local-dev:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "9000:8080"
    volumes:
      - ${PWD}/lambda:/var/task/lambda
      - ${HOME}/.aws:/root/.aws/:ro
